name: Build and SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Full clone for better SonarCloud analysis

      # Step 2: Set up JDK 17 (required by the Android Gradle Plugin)
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Set up Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33         # Replace with the API level your project targets
          target: default
          channel: 3            # Stable channel for SDK components

      # Step 4: Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Step 5: Run Tests with Coverage
      - name: Run Tests with Coverage
        run: ./gradlew app:jacocoTestReport

      # Step 6: Run SonarCloud Analysis with Coverage Report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ofonsecan_vinilos-4203-2023-15
            -Dsonar.organization=ofonsecan
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
